import type { SocialComment, SocialPost, SocialUser } from './types'

export const CURRENT_USER_ID = 'me'

export const mockCurrentUser: SocialUser = {
  id: CURRENT_USER_ID,
  username: 'fernandorm',
  displayName: 'Fernando RM',
  avatarUrl: 'https://i.pravatar.cc/160?img=14',
  bio: 'Construyendo una comunidad saludable plato a plato.',
  followersCount: 42,
  followingCount: 18,
  relationshipWithMe: {
    followStatus: 'following',
    friendshipStatus: 'friends',
  },
}

export const mockUsers: SocialUser[] = [
  {
    id: 'usr-lucia',
    username: 'nutri_lucia',
    displayName: 'Lucia Mendez',
    avatarUrl: 'https://i.pravatar.cc/160?img=32',
    bio: 'Nutricion practica y recetas rapidas para el dia a dia.',
    followersCount: 128,
    followingCount: 76,
    relationshipWithMe: {
      followStatus: 'not_following',
      friendshipStatus: 'none',
    },
  },
  {
    id: 'usr-marcos',
    username: 'chefmarcos',
    displayName: 'Marcos Ruiz',
    avatarUrl: 'https://i.pravatar.cc/160?img=12',
    bio: 'Batch cooking y comida real para semanas con poco tiempo.',
    followersCount: 203,
    followingCount: 92,
    relationshipWithMe: {
      followStatus: 'not_following',
      friendshipStatus: 'none',
    },
  },
  {
    id: 'usr-andrea',
    username: 'verde_andrea',
    displayName: 'Andrea Gil',
    avatarUrl: 'https://i.pravatar.cc/160?img=47',
    bio: 'Ideas frescas de mercado y platos ligeros de temporada.',
    followersCount: 167,
    followingCount: 61,
    relationshipWithMe: {
      followStatus: 'not_following',
      friendshipStatus: 'none',
    },
  },
]

export const mockPosts: SocialPost[] = [
  {
    id: 'post-lucia-1',
    authorId: 'usr-lucia',
    imageUrl: 'https://picsum.photos/seed/lucia-breakfast/960/720',
    title: 'Tostada proteica con huevo y aguacate',
    caption: 'Desayuno alto en proteina listo en menos de 8 minutos.',
    createdAt: '2026-04-08T09:10:00.000Z',
    likesCount: 83,
    interactionsCount: 19,
    recipe: {
      title: 'Tostada proteica con huevo y aguacate',
      description: 'Una opcion rapida para arrancar el dia con saciedad y energia estable.',
      difficulty: 'Facil',
      prepTimeMinutes: 8,
      servings: 1,
      calories: 430,
      protein: 27,
      carbs: 28,
      fat: 22,
      ingredients: [
        { name: 'Pan integral', amount: '2 rebanadas' },
        { name: 'Huevos', amount: '2 unidades' },
        { name: 'Aguacate', amount: '1/2 pieza' },
        { name: 'Semillas de chia', amount: '1 cucharadita' },
      ],
      steps: [
        'Tosta el pan hasta que quede crujiente.',
        'Cocina los huevos a la plancha o revueltos.',
        'Machaca el aguacate y reparte sobre el pan.',
        'Añade el huevo y termina con chia y pimienta.',
      ],
    },
  },
  {
    id: 'post-lucia-2',
    authorId: 'usr-lucia',
    imageUrl: 'https://picsum.photos/seed/lucia-snack/960/720',
    title: 'Bol de yogur post-entreno',
    caption: 'Snack post-entreno: yogur, frutos rojos y semillas.',
    createdAt: '2026-04-07T15:20:00.000Z',
    likesCount: 54,
    interactionsCount: 12,
    recipe: {
      title: 'Bol de yogur post-entreno',
      description: 'Perfecto para recuperar proteina y meter fruta sin cocinar nada.',
      difficulty: 'Facil',
      prepTimeMinutes: 5,
      servings: 1,
      calories: 290,
      protein: 21,
      carbs: 24,
      fat: 10,
      ingredients: [
        { name: 'Yogur griego natural', amount: '200 g' },
        { name: 'Frutos rojos', amount: '80 g' },
        { name: 'Granola', amount: '25 g' },
        { name: 'Semillas de calabaza', amount: '10 g' },
      ],
      steps: [
        'Sirve el yogur en un bol frio.',
        'Añade frutos rojos y granola por capas.',
        'Termina con semillas para textura.',
      ],
    },
  },
  {
    id: 'post-marcos-1',
    authorId: 'usr-marcos',
    imageUrl: 'https://picsum.photos/seed/marcos-bowl/960/720',
    title: 'Bowl completo de pollo especiado',
    caption: 'Bowl de arroz integral con pollo especiado y vegetales.',
    createdAt: '2026-04-08T07:45:00.000Z',
    likesCount: 97,
    interactionsCount: 25,
    recipe: {
      title: 'Bowl completo de pollo especiado',
      description: 'Comida equilibrada para preparar varias raciones en un solo salteado.',
      difficulty: 'Media',
      prepTimeMinutes: 22,
      servings: 2,
      calories: 560,
      protein: 42,
      carbs: 51,
      fat: 18,
      ingredients: [
        { name: 'Arroz integral cocido', amount: '240 g' },
        { name: 'Pechuga de pollo', amount: '300 g' },
        { name: 'Brocoli', amount: '150 g' },
        { name: 'Pimiento rojo', amount: '1 unidad' },
      ],
      steps: [
        'Dora el pollo con pimenton, ajo y comino.',
        'Saltea las verduras manteniendo textura.',
        'Sirve sobre arroz integral caliente.',
        'Añade un toque de limon antes de comer.',
      ],
    },
  },
  {
    id: 'post-marcos-2',
    authorId: 'usr-marcos',
    imageUrl: 'https://picsum.photos/seed/marcos-prep/960/720',
    title: 'Batch cooking de domingo',
    caption: 'Domingo de batch cooking: 4 comidas preparadas en 1 hora.',
    createdAt: '2026-04-06T19:40:00.000Z',
    likesCount: 131,
    interactionsCount: 33,
    recipe: {
      title: 'Batch cooking de domingo',
      description: 'Base semanal con proteina, carbohidrato complejo y verduras listas.',
      difficulty: 'Media',
      prepTimeMinutes: 60,
      servings: 4,
      calories: 610,
      protein: 38,
      carbs: 58,
      fat: 21,
      ingredients: [
        { name: 'Pavo picado', amount: '600 g' },
        { name: 'Boniato', amount: '800 g' },
        { name: 'Judias verdes', amount: '400 g' },
        { name: 'Aceite de oliva', amount: '2 cucharadas' },
      ],
      steps: [
        'Asa el boniato en dados hasta que caramelice.',
        'Cocina el pavo con especias suaves.',
        'Cuece o saltea las judias verdes.',
        'Reparte en cuatro tuppers con el mismo peso.',
      ],
    },
  },
  {
    id: 'post-andrea-1',
    authorId: 'usr-andrea',
    imageUrl: 'https://picsum.photos/seed/andrea-salad/960/720',
    title: 'Ensalada crunchy de garbanzos',
    caption: 'Ensalada crunchy con garbanzos y vinagreta citrica.',
    createdAt: '2026-04-08T10:55:00.000Z',
    likesCount: 74,
    interactionsCount: 17,
    recipe: {
      title: 'Ensalada crunchy de garbanzos',
      description: 'Ligera, fresca y con contraste de texturas para una comida rapida.',
      difficulty: 'Facil',
      prepTimeMinutes: 12,
      servings: 2,
      calories: 380,
      protein: 16,
      carbs: 34,
      fat: 18,
      ingredients: [
        { name: 'Garbanzos cocidos', amount: '250 g' },
        { name: 'Pepino', amount: '1 unidad' },
        { name: 'Canónigos', amount: '80 g' },
        { name: 'Limon', amount: '1 unidad' },
      ],
      steps: [
        'Seca bien los garbanzos y saltéalos dos minutos.',
        'Mezcla hojas verdes y pepino laminado.',
        'Prepara vinagreta con limon y aceite.',
        'Junta todo justo antes de servir.',
      ],
    },
  },
  {
    id: 'post-andrea-2',
    authorId: 'usr-andrea',
    imageUrl: 'https://picsum.photos/seed/andrea-market/960/720',
    title: 'Compra fresca para toda la semana',
    caption: 'Compra inteligente: productos frescos para toda la semana.',
    createdAt: '2026-04-07T11:05:00.000Z',
    likesCount: 66,
    interactionsCount: 14,
    recipe: {
      title: 'Compra fresca para toda la semana',
      description: 'Plantilla sencilla para cocinar platos versatiles con la misma compra.',
      difficulty: 'Facil',
      prepTimeMinutes: 15,
      servings: 3,
      calories: 340,
      protein: 14,
      carbs: 29,
      fat: 17,
      ingredients: [
        { name: 'Verduras de hoja', amount: '2 bolsas' },
        { name: 'Tomate cherry', amount: '250 g' },
        { name: 'Queso fresco', amount: '180 g' },
        { name: 'Fruta de temporada', amount: '6 piezas' },
      ],
      steps: [
        'Lava y seca toda la verdura al llegar a casa.',
        'Guarda en recipientes separados por uso.',
        'Deja una base lista para ensaladas y bowls.',
      ],
    },
  },
]

export const mockComments: SocialComment[] = [
  {
    id: 'comment-1',
    postId: 'post-lucia-1',
    authorId: 'usr-marcos',
    message: '¿Le metes alguna salsa ligera o solo especias?',
    createdAt: '2026-04-08T09:32:00.000Z',
  },
  {
    id: 'comment-2',
    postId: 'post-lucia-1',
    authorId: 'usr-lucia',
    message: 'Solo pimienta, limon y un toque de queso batido si quiero mas cremosidad.',
    createdAt: '2026-04-08T09:38:00.000Z',
  },
  {
    id: 'comment-3',
    postId: 'post-marcos-1',
    authorId: 'usr-andrea',
    message: 'Buenisimo para meal prep. ¿Cuanto aguanta en nevera?',
    createdAt: '2026-04-08T08:12:00.000Z',
  },
  {
    id: 'comment-4',
    postId: 'post-marcos-1',
    authorId: 'usr-marcos',
    message: 'Dos dias perfecto. Si haces mas, mejor congela el pollo aparte.',
    createdAt: '2026-04-08T08:20:00.000Z',
  },
  {
    id: 'comment-5',
    postId: 'post-andrea-1',
    authorId: 'me',
    message: 'La vinagreta citrica aqui cambia todo. ¿Usas mostaza tambien?',
    createdAt: '2026-04-08T11:20:00.000Z',
  },
]
